<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'О нас';
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
    
<p></p>
<p><span><span style="font-size: small;">Воронежская Лига Дворового Футбола (ВЛДФ)</span> образовалась в 2009 году, именно в том году группой энтузиастов &ndash; любителей футбола был проведен первый турнир на 16 команд. Историю развития ВЛДФ можно найти на наших интернет ресурсах: сайт&nbsp;</span><a href="http://vk.com/away.php?to=http%3A%2F%2Fvldf.ru%2F" target="_blank">http://vldf.ru/</a><span>, группа в &laquo;ВКонтакте&raquo;&nbsp;</span><a href="https://vk.com/vldfru" target="_blank">https://vk.com/vldfru</a><span>. Необходимо отметить, что 6 лет прошло в динамичном поступательном развитии.&nbsp;</span></p>
<p><br /><span style="font-size: small;">На сегодня ВЛДФ это:&nbsp;</span><br /><span>- 100 действующих непрофессиональных футбольных команд;&nbsp;</span><br /><span>- 10 футбольных турниров в течение всего календарного года</span> <a href="http://vk.com/away.php?to=http%3A%2F%2Fvldf.ru%2Fturnirall%2F" target="_blank">http://vldf.ru/turnirall/</a><span>;&nbsp;</span><br /><span>- 1700 человек принимающих участие в турнирах;&nbsp;</span><br /><span>- 950 часов футбола в год &ndash; это только официальных соревнований, без учета товарищеских игр и тренировок;&nbsp;</span><br /><span>- Профессиональный сайт&nbsp;</span><a href="http://vk.com/away.php?to=http%3A%2F%2Fvldf.ru%2F" target="_blank">http://vldf.ru/</a><span>&nbsp;со статистикой по каждому игроку за все прошлые годы;&nbsp;</span><br /><span>- Группа в &laquo;ВКонтакте&raquo; численностью 5000+ человек (игроки и их близкие)&nbsp;</span><a href="https://vk.com/vldfru" target="_blank">https://vk.com/vldfru</a><span>;&nbsp;</span><br /><span>- Профессиональные фото с каждого матча&nbsp;</span><a href="https://vk.com/albums-52065204" target="_blank">https://vk.com/albums-52065204</a><span>;&nbsp;</span><br /><span>- Видеоотчеты с центральных игр&nbsp;</span><a href="https://vk.com/videos-2058590" target="_blank">https://vk.com/videos-2058590</a><span>;&nbsp;</span><br /><span>- Еженедельная обзорная программа о событиях в лиге (достаточно ввести в поисковике на&nbsp;</span><a href="http://vk.com/away.php?to=http%3A%2F%2Fwww.youtube.com%2F" target="_blank">http://www.youtube.com/</a><span>&nbsp;ВЛДФ, все станет очевидно);&nbsp;</span><br /><span>- Профессиональный судейский корпус&nbsp;</span><a href="http://vk.com/away.php?to=http%3A%2F%2Fvldf.ru%2Freferies%2F" target="_blank">http://vldf.ru/referies/</a><span>;&nbsp;</span><br /><span>- Команда организаторов с семилетним опытом работы;&nbsp;</span><br /><span>- Масса амбициозных планов.&nbsp;</span></p>
<p><br /><span><span style="font-size: small;">Планы ВЛДФ:</span>&nbsp;</span><br /><span>- Улучшение качества проведения существующих соревнований;&nbsp;</span><br /><span>- Углубление в регионы области (до каждой деревни), привлечение местного населения к проведению у себя своих соревнований, обучение энтузиастов на местах;&nbsp;</span><br /><span>- Выход на федеральный уровень, обеспечение участия чемпионов в первой лиге чемпионата России по мини-футболу, создание межрегиональных любительских соревнований;&nbsp;</span><br /><span>- Развитие других видов футбола;&nbsp;</span><br /><span>- Развитие корпоративного футбола;&nbsp;</span><br /><span>- Строительство собственных спортивных объектов.&nbsp;</span></p>
<p><br /><span style="font-size: small;">Приглашаем к сотрудничеству. Мы готовы выслушать ваши идеи и продумать пути возможного развития наших деловых отношений.</span></p>
</div>
